### ISSUE TITLE
séquences

### ISSUE THREAD

**Issue by iambluedev1** [Julien00859/Julien00859.github.io#2]
Angle : 17
Séquence : [9,8,4,2,5,11,4,4,0,7,8,16,14,8,15]
https://i.imgur.com/it7BiCS.png
--
Angle: 4
Seq : [0,0,0,1,0,1,2,1,1,1,0,1,1,1,1]
Piques: oui
https://i.imgur.com/tCBB8dJ.png
--
Angle : 17
Séquence : [15,8,6,13,15,8,4,7,3,6,2,10,3,8,15]
https://i.imgur.com/uJljA4a.png
--
Angle : 25
Séquence : [13,22,18,12,18,4,19,9,9,0,20,17,6,0,12]
https://i.imgur.com/TXfekAV.png

**Comment by Julien00859** [comment]
:+1:
